### ISSUE TITLE
Create documentation with Sphinx

### ISSUE THREAD

**Issue by AdrienChassignet** [M05-project-group5/mini-project#9]
Setup the doc with Sphinx and eventually GitHub pages.

**Comment by mariethoz** [comment]
GitHub pages
This is just the indication where we take the documentation. The idea is to use a specific 'gh-pages' branch where the documentation is stored in html format. Then we can normally see the site under M05-project-group5.github.io/mini-project/index.html.

**Comment by mariethoz** [comment]
The documentation with Sphinx and GitHub pages is done when a tag is push.
The code for that is in the continous integration.
